# Generated by Django 5.0.9 on 2026-07-03 20:31

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disciplines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('architect', 'Architect'), ('civil_engineer', 'Civil Engineer'), ('structural_engineer', 'Structural Engineer'), ('qs', 'Quantity Surveyor'), ('contractor', 'Contractor'), ('site_supervisor', 'Site Supervisor'), ('project_manager', 'Project Manager'), ('interior_designer', 'Interior Designer'), ('mep_engineer', 'MEP Engineer')], max_length=30), blank=True, default=list, help_text='Multi-select from the Discipline taxonomy.', size=None)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('location_text', models.CharField(blank=True, max_length=200, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
