# Generated by Django 5.0.9 on 2026-07-04 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_text', models.CharField(blank=True, max_length=300, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('connections', 'Connections'), ('private', 'Private')], default='public', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline', models.CharField(choices=[('architect', 'Architect'), ('civil_engineer', 'Civil Engineer'), ('structural_engineer', 'Structural Engineer'), ('qs', 'Quantity Surveyor'), ('contractor', 'Contractor'), ('site_supervisor', 'Site Supervisor'), ('project_manager', 'Project Manager'), ('interior_designer', 'Interior Designer'), ('mep_engineer', 'MEP Engineer')], max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='projects.project')),
            ],
            options={
                'db_table': 'project_disciplines',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='proj_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility', 'is_deleted'], name='proj_visibility_del_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectdiscipline',
            constraint=models.UniqueConstraint(fields=('project', 'discipline'), name='unique_project_discipline'),
        ),
    ]
