import os

from .base import *  # noqa: F401,F403

DEBUG = False

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SIMPLE_JWT["ALGORITHM"] = "RS256"  # noqa: F405
SIMPLE_JWT["SIGNING_KEY"] = os.environ["JWT_SIGNING_KEY"]  # noqa: F405
SIMPLE_JWT["VERIFYING_KEY"] = os.environ["JWT_VERIFYING_KEY"]  # noqa: F405

LOGGING["root"]["level"] = "WARNING"  # noqa: F405
