# Generated by Django 5.0.9 on 2026-07-04 16:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("milestone", "Milestone"),
                            ("daily_log", "Daily Log"),
                            ("issue", "Issue / Resolution"),
                            ("inspection", "Inspection Passed"),
                            ("phase_complete", "Phase Complete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entry_date", models.DateField()),
                (
                    "geotag_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "geotag_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("exif_metadata", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_updates",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UpdatePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cloudinary_public_id", models.CharField(max_length=300)),
                ("url", models.URLField(max_length=500)),
                (
                    "sequence_order",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="build_log.projectupdate",
                    ),
                ),
            ],
            options={
                "db_table": "update_photos",
                "ordering": ["sequence_order"],
            },
        ),
        migrations.AddIndex(
            model_name="projectupdate",
            index=models.Index(
                fields=["project", "entry_date"], name="update_proj_entrydate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectupdate",
            index=models.Index(
                fields=["author", "created_at"], name="update_author_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="updatephoto",
            constraint=models.UniqueConstraint(
                fields=("update", "sequence_order"), name="unique_update_sequence_order"
            ),
        ),
    ]
