# Generated by Django 5.0.9 on 2026-07-15 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterestSignup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("construction_firm", "Construction Firm"),
                            ("educational_institution", "Educational Institution"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "source_page",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "interest_signups",
                "indexes": [
                    models.Index(
                        fields=["interest_type", "-created_at"],
                        name="lead_type_created_idx",
                    )
                ],
            },
        ),
    ]
